### ISSUE TITLE
Lien a fix dans la nav bar du index.html

### ISSUE THREAD

**Issue by AzmogEx** [Bts-Sio-CCI/FlowTech#2]
<img width="1183" alt="Capture d’écran 2023-12-18 à 09 42 44" src="https://github.com/Bts-Sio-CCI/FlowTech/assets/80716388/e9146616-49cc-4dd9-92dd-87621682c095">
<img width="1211" alt="Capture d’écran 2023-12-18 à 09 42 59" src="https://github.com/Bts-Sio-CCI/FlowTech/assets/80716388/290097df-4f9b-4505-819f-ebc1eb748aa0">

**Lien a fix dans la nav bar du index.html**

**Comment by spitzerl** [comment]
Lien retiré 👍🏼
