### ISSUE TITLE
Card alignement

### ISSUE THREAD

**Issue by AzmogEx** [Bts-Sio-CCI/FlowTech#3]
**Aligner la card PC omega avec les autres**

<img width="1226" alt="Capture d’écran 2023-12-18 à 09 44 19" src="https://github.com/Bts-Sio-CCI/FlowTech/assets/80716388/f779b72b-b4d1-4cb1-b2dc-e132f9904435">

**Comment by spitzerl** [comment]
Réglé 👍🏼
